-- OBTENER EL TOTAL DE PEDIDOS REALIZADOS POR CADA USUARIO REGISTRADO EN LA TABLA USUARIOS ORDENANDO POR EL TOTAL DE PEDIDOS

SELECT nombre, COUNT(*) AS total_pedidos
FROM Usuarios JOIN Pedidos ON Usuarios.id = Pedidos.usuarios.id GROUP BY Usuarios.id ORDER BY total_pedidos DESC;

